"""add source column to transactions

Revision ID: 69e4f3ee4a95
Revises: cec0498a7d25
Create Date: 2026-09-05 19:16:52.878230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69e4f3ee4a95'
down_revision: Union[str, Sequence[str], None] = 'cec0498a7d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='paysim_sim' does double duty: Postgres backfills every
    # pre-existing row to "paysim_sim" as part of this ADD COLUMN (all prior
    # traffic -- the simulator, POST /predict, Test a Transaction -- was
    # scored through the PaySim-shaped schema, so that's the correct
    # historical value, not NULL), and it's also a safety-net default for any
    # future insert that doesn't explicitly pass `source`. The ORM layer
    # (app/db/models.py, app/services/prediction_service.py) always passes
    # `source` explicitly going forward -- see CLAUDE.md's Phase 9 part 2.
    op.add_column('transactions', sa.Column('source', sa.String(), server_default='paysim_sim', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'source')
    # ### end Alembic commands ###
